version: "3.8"

services:
  front-angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: front-angular-container
    ports:
      - "4200:80" # Puerto de tu máquina:puerto del contenedor
    restart: unless-stopped
